# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc import checkpoints_pb2 as checkpoints__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in checkpoints_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReproduccionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCheckpoint = channel.unary_unary(
                '/reproduccion.ReproduccionService/GetCheckpoint',
                request_serializer=checkpoints__pb2.CheckpointRequest.SerializeToString,
                response_deserializer=checkpoints__pb2.CheckpointResponse.FromString,
                _registered_method=True)
        self.GetVideoStats = channel.unary_unary(
                '/reproduccion.ReproduccionService/GetVideoStats',
                request_serializer=checkpoints__pb2.VideoStatsRequest.SerializeToString,
                response_deserializer=checkpoints__pb2.VideoStatsResponse.FromString,
                _registered_method=True)
        self.GetUserProgress = channel.unary_unary(
                '/reproduccion.ReproduccionService/GetUserProgress',
                request_serializer=checkpoints__pb2.UserProgressRequest.SerializeToString,
                response_deserializer=checkpoints__pb2.UserProgressResponse.FromString,
                _registered_method=True)


class ReproduccionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVideoStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReproduccionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCheckpoint,
                    request_deserializer=checkpoints__pb2.CheckpointRequest.FromString,
                    response_serializer=checkpoints__pb2.CheckpointResponse.SerializeToString,
            ),
            'GetVideoStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVideoStats,
                    request_deserializer=checkpoints__pb2.VideoStatsRequest.FromString,
                    response_serializer=checkpoints__pb2.VideoStatsResponse.SerializeToString,
            ),
            'GetUserProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserProgress,
                    request_deserializer=checkpoints__pb2.UserProgressRequest.FromString,
                    response_serializer=checkpoints__pb2.UserProgressResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reproduccion.ReproduccionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('reproduccion.ReproduccionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReproduccionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reproduccion.ReproduccionService/GetCheckpoint',
            checkpoints__pb2.CheckpointRequest.SerializeToString,
            checkpoints__pb2.CheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVideoStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reproduccion.ReproduccionService/GetVideoStats',
            checkpoints__pb2.VideoStatsRequest.SerializeToString,
            checkpoints__pb2.VideoStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reproduccion.ReproduccionService/GetUserProgress',
            checkpoints__pb2.UserProgressRequest.SerializeToString,
            checkpoints__pb2.UserProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
