# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: checkpoints.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'checkpoints.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63heckpoints.proto\x12\x0creproduccion\"6\n\x11\x43heckpointRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08video_id\x18\x02 \x01(\t\"~\n\x12\x43heckpointResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08video_id\x18\x02 \x01(\t\x12\x18\n\x10position_seconds\x18\x03 \x01(\x05\x12\x18\n\x10progress_percent\x18\x04 \x01(\x02\x12\x11\n\tcompleted\x18\x05 \x01(\x08\"%\n\x11VideoStatsRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\"u\n\x12VideoStatsResponse\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\x13\n\x0btotal_views\x18\x02 \x01(\x05\x12\x18\n\x10\x61verage_progress\x18\x03 \x01(\x02\x12\x1e\n\x16recommendation_percent\x18\x04 \x01(\x02\"9\n\x13UserProgressRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tcourse_id\x18\x02 \x01(\t\"\x81\x01\n\x14UserProgressResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tcourse_id\x18\x02 \x01(\t\x12\x18\n\x10overall_progress\x18\x03 \x01(\x02\x12+\n\x06videos\x18\x04 \x03(\x0b\x32\x1b.reproduccion.VideoProgress\"N\n\rVideoProgress\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\x18\n\x10progress_percent\x18\x02 \x01(\x02\x12\x11\n\tcompleted\x18\x03 \x01(\x08\x32\x97\x02\n\x13ReproduccionService\x12R\n\rGetCheckpoint\x12\x1f.reproduccion.CheckpointRequest\x1a .reproduccion.CheckpointResponse\x12R\n\rGetVideoStats\x12\x1f.reproduccion.VideoStatsRequest\x1a .reproduccion.VideoStatsResponse\x12X\n\x0fGetUserProgress\x12!.reproduccion.UserProgressRequest\x1a\".reproduccion.UserProgressResponseB\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'checkpoints_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_CHECKPOINTREQUEST']._serialized_start=35
  _globals['_CHECKPOINTREQUEST']._serialized_end=89
  _globals['_CHECKPOINTRESPONSE']._serialized_start=91
  _globals['_CHECKPOINTRESPONSE']._serialized_end=217
  _globals['_VIDEOSTATSREQUEST']._serialized_start=219
  _globals['_VIDEOSTATSREQUEST']._serialized_end=256
  _globals['_VIDEOSTATSRESPONSE']._serialized_start=258
  _globals['_VIDEOSTATSRESPONSE']._serialized_end=375
  _globals['_USERPROGRESSREQUEST']._serialized_start=377
  _globals['_USERPROGRESSREQUEST']._serialized_end=434
  _globals['_USERPROGRESSRESPONSE']._serialized_start=437
  _globals['_USERPROGRESSRESPONSE']._serialized_end=566
  _globals['_VIDEOPROGRESS']._serialized_start=568
  _globals['_VIDEOPROGRESS']._serialized_end=646
  _globals['_REPRODUCCIONSERVICE']._serialized_start=649
  _globals['_REPRODUCCIONSERVICE']._serialized_end=928
# @@protoc_insertion_point(module_scope)
