// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: checkpoints.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointRequest) Reset() {
	*x = CheckpointRequest{}
	mi := &file_checkpoints_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointRequest) ProtoMessage() {}

func (x *CheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointRequest.ProtoReflect.Descriptor instead.
func (*CheckpointRequest) Descriptor() ([]byte, []int) {
	return file_checkpoints_proto_rawDescGZIP(), []int{0}
}

func (x *CheckpointRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckpointRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type CheckpointResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId         string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	PositionSeconds int32                  `protobuf:"varint,3,opt,name=position_seconds,json=positionSeconds,proto3" json:"position_seconds,omitempty"`
	ProgressPercent float32                `protobuf:"fixed32,4,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	Completed       bool                   `protobuf:"varint,5,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckpointResponse) Reset() {
	*x = CheckpointResponse{}
	mi := &file_checkpoints_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointResponse) ProtoMessage() {}

func (x *CheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointResponse.ProtoReflect.Descriptor instead.
func (*CheckpointResponse) Descriptor() ([]byte, []int) {
	return file_checkpoints_proto_rawDescGZIP(), []int{1}
}

func (x *CheckpointResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckpointResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *CheckpointResponse) GetPositionSeconds() int32 {
	if x != nil {
		return x.PositionSeconds
	}
	return 0
}

func (x *CheckpointResponse) GetProgressPercent() float32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *CheckpointResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type VideoStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoStatsRequest) Reset() {
	*x = VideoStatsRequest{}
	mi := &file_checkpoints_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoStatsRequest) ProtoMessage() {}

func (x *VideoStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoStatsRequest.ProtoReflect.Descriptor instead.
func (*VideoStatsRequest) Descriptor() ([]byte, []int) {
	return file_checkpoints_proto_rawDescGZIP(), []int{2}
}

func (x *VideoStatsRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type VideoStatsResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	VideoId               string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	TotalViews            int32                  `protobuf:"varint,2,opt,name=total_views,json=totalViews,proto3" json:"total_views,omitempty"`
	AverageProgress       float32                `protobuf:"fixed32,3,opt,name=average_progress,json=averageProgress,proto3" json:"average_progress,omitempty"`
	RecommendationPercent float32                `protobuf:"fixed32,4,opt,name=recommendation_percent,json=recommendationPercent,proto3" json:"recommendation_percent,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VideoStatsResponse) Reset() {
	*x = VideoStatsResponse{}
	mi := &file_checkpoints_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoStatsResponse) ProtoMessage() {}

func (x *VideoStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoStatsResponse.ProtoReflect.Descriptor instead.
func (*VideoStatsResponse) Descriptor() ([]byte, []int) {
	return file_checkpoints_proto_rawDescGZIP(), []int{3}
}

func (x *VideoStatsResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *VideoStatsResponse) GetTotalViews() int32 {
	if x != nil {
		return x.TotalViews
	}
	return 0
}

func (x *VideoStatsResponse) GetAverageProgress() float32 {
	if x != nil {
		return x.AverageProgress
	}
	return 0
}

func (x *VideoStatsResponse) GetRecommendationPercent() float32 {
	if x != nil {
		return x.RecommendationPercent
	}
	return 0
}

type UserProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProgressRequest) Reset() {
	*x = UserProgressRequest{}
	mi := &file_checkpoints_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProgressRequest) ProtoMessage() {}

func (x *UserProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProgressRequest.ProtoReflect.Descriptor instead.
func (*UserProgressRequest) Descriptor() ([]byte, []int) {
	return file_checkpoints_proto_rawDescGZIP(), []int{4}
}

func (x *UserProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProgressRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type UserProgressResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId        string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	OverallProgress float32                `protobuf:"fixed32,3,opt,name=overall_progress,json=overallProgress,proto3" json:"overall_progress,omitempty"`
	Videos          []*VideoProgress       `protobuf:"bytes,4,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserProgressResponse) Reset() {
	*x = UserProgressResponse{}
	mi := &file_checkpoints_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProgressResponse) ProtoMessage() {}

func (x *UserProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProgressResponse.ProtoReflect.Descriptor instead.
func (*UserProgressResponse) Descriptor() ([]byte, []int) {
	return file_checkpoints_proto_rawDescGZIP(), []int{5}
}

func (x *UserProgressResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProgressResponse) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *UserProgressResponse) GetOverallProgress() float32 {
	if x != nil {
		return x.OverallProgress
	}
	return 0
}

func (x *UserProgressResponse) GetVideos() []*VideoProgress {
	if x != nil {
		return x.Videos
	}
	return nil
}

type VideoProgress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VideoId         string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	ProgressPercent float32                `protobuf:"fixed32,2,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	Completed       bool                   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VideoProgress) Reset() {
	*x = VideoProgress{}
	mi := &file_checkpoints_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoProgress) ProtoMessage() {}

func (x *VideoProgress) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoints_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoProgress.ProtoReflect.Descriptor instead.
func (*VideoProgress) Descriptor() ([]byte, []int) {
	return file_checkpoints_proto_rawDescGZIP(), []int{6}
}

func (x *VideoProgress) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *VideoProgress) GetProgressPercent() float32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *VideoProgress) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

var File_checkpoints_proto protoreflect.FileDescriptor

const file_checkpoints_proto_rawDesc = "" +
	"\n" +
	"\x11checkpoints.proto\x12\freproduccion\"G\n" +
	"\x11CheckpointRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\"\xbc\x01\n" +
	"\x12CheckpointResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\x12)\n" +
	"\x10position_seconds\x18\x03 \x01(\x05R\x0fpositionSeconds\x12)\n" +
	"\x10progress_percent\x18\x04 \x01(\x02R\x0fprogressPercent\x12\x1c\n" +
	"\tcompleted\x18\x05 \x01(\bR\tcompleted\".\n" +
	"\x11VideoStatsRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"\xb2\x01\n" +
	"\x12VideoStatsResponse\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x1f\n" +
	"\vtotal_views\x18\x02 \x01(\x05R\n" +
	"totalViews\x12)\n" +
	"\x10average_progress\x18\x03 \x01(\x02R\x0faverageProgress\x125\n" +
	"\x16recommendation_percent\x18\x04 \x01(\x02R\x15recommendationPercent\"K\n" +
	"\x13UserProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"\xac\x01\n" +
	"\x14UserProgressResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12)\n" +
	"\x10overall_progress\x18\x03 \x01(\x02R\x0foverallProgress\x123\n" +
	"\x06videos\x18\x04 \x03(\v2\x1b.reproduccion.VideoProgressR\x06videos\"s\n" +
	"\rVideoProgress\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12)\n" +
	"\x10progress_percent\x18\x02 \x01(\x02R\x0fprogressPercent\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\bR\tcompleted2\x97\x02\n" +
	"\x13ReproduccionService\x12R\n" +
	"\rGetCheckpoint\x12\x1f.reproduccion.CheckpointRequest\x1a .reproduccion.CheckpointResponse\x12R\n" +
	"\rGetVideoStats\x12\x1f.reproduccion.VideoStatsRequest\x1a .reproduccion.VideoStatsResponse\x12X\n" +
	"\x0fGetUserProgress\x12!.reproduccion.UserProgressRequest\x1a\".reproduccion.UserProgressResponseB\tZ\a./protob\x06proto3"

var (
	file_checkpoints_proto_rawDescOnce sync.Once
	file_checkpoints_proto_rawDescData []byte
)

func file_checkpoints_proto_rawDescGZIP() []byte {
	file_checkpoints_proto_rawDescOnce.Do(func() {
		file_checkpoints_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_checkpoints_proto_rawDesc), len(file_checkpoints_proto_rawDesc)))
	})
	return file_checkpoints_proto_rawDescData
}

var file_checkpoints_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_checkpoints_proto_goTypes = []any{
	(*CheckpointRequest)(nil),    // 0: reproduccion.CheckpointRequest
	(*CheckpointResponse)(nil),   // 1: reproduccion.CheckpointResponse
	(*VideoStatsRequest)(nil),    // 2: reproduccion.VideoStatsRequest
	(*VideoStatsResponse)(nil),   // 3: reproduccion.VideoStatsResponse
	(*UserProgressRequest)(nil),  // 4: reproduccion.UserProgressRequest
	(*UserProgressResponse)(nil), // 5: reproduccion.UserProgressResponse
	(*VideoProgress)(nil),        // 6: reproduccion.VideoProgress
}
var file_checkpoints_proto_depIdxs = []int32{
	6, // 0: reproduccion.UserProgressResponse.videos:type_name -> reproduccion.VideoProgress
	0, // 1: reproduccion.ReproduccionService.GetCheckpoint:input_type -> reproduccion.CheckpointRequest
	2, // 2: reproduccion.ReproduccionService.GetVideoStats:input_type -> reproduccion.VideoStatsRequest
	4, // 3: reproduccion.ReproduccionService.GetUserProgress:input_type -> reproduccion.UserProgressRequest
	1, // 4: reproduccion.ReproduccionService.GetCheckpoint:output_type -> reproduccion.CheckpointResponse
	3, // 5: reproduccion.ReproduccionService.GetVideoStats:output_type -> reproduccion.VideoStatsResponse
	5, // 6: reproduccion.ReproduccionService.GetUserProgress:output_type -> reproduccion.UserProgressResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_checkpoints_proto_init() }
func file_checkpoints_proto_init() {
	if File_checkpoints_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_checkpoints_proto_rawDesc), len(file_checkpoints_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_checkpoints_proto_goTypes,
		DependencyIndexes: file_checkpoints_proto_depIdxs,
		MessageInfos:      file_checkpoints_proto_msgTypes,
	}.Build()
	File_checkpoints_proto = out.File
	file_checkpoints_proto_goTypes = nil
	file_checkpoints_proto_depIdxs = nil
}
