// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: checkpoints.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReproduccionService_GetCheckpoint_FullMethodName   = "/reproduccion.ReproduccionService/GetCheckpoint"
	ReproduccionService_GetVideoStats_FullMethodName   = "/reproduccion.ReproduccionService/GetVideoStats"
	ReproduccionService_GetUserProgress_FullMethodName = "/reproduccion.ReproduccionService/GetUserProgress"
)

// ReproduccionServiceClient is the client API for ReproduccionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReproduccionServiceClient interface {
	GetCheckpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error)
	GetVideoStats(ctx context.Context, in *VideoStatsRequest, opts ...grpc.CallOption) (*VideoStatsResponse, error)
	GetUserProgress(ctx context.Context, in *UserProgressRequest, opts ...grpc.CallOption) (*UserProgressResponse, error)
}

type reproduccionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReproduccionServiceClient(cc grpc.ClientConnInterface) ReproduccionServiceClient {
	return &reproduccionServiceClient{cc}
}

func (c *reproduccionServiceClient) GetCheckpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointResponse)
	err := c.cc.Invoke(ctx, ReproduccionService_GetCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reproduccionServiceClient) GetVideoStats(ctx context.Context, in *VideoStatsRequest, opts ...grpc.CallOption) (*VideoStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoStatsResponse)
	err := c.cc.Invoke(ctx, ReproduccionService_GetVideoStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reproduccionServiceClient) GetUserProgress(ctx context.Context, in *UserProgressRequest, opts ...grpc.CallOption) (*UserProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProgressResponse)
	err := c.cc.Invoke(ctx, ReproduccionService_GetUserProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReproduccionServiceServer is the server API for ReproduccionService service.
// All implementations must embed UnimplementedReproduccionServiceServer
// for forward compatibility.
type ReproduccionServiceServer interface {
	GetCheckpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error)
	GetVideoStats(context.Context, *VideoStatsRequest) (*VideoStatsResponse, error)
	GetUserProgress(context.Context, *UserProgressRequest) (*UserProgressResponse, error)
	mustEmbedUnimplementedReproduccionServiceServer()
}

// UnimplementedReproduccionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReproduccionServiceServer struct{}

func (UnimplementedReproduccionServiceServer) GetCheckpoint(context.Context, *CheckpointRequest) (*CheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCheckpoint not implemented")
}
func (UnimplementedReproduccionServiceServer) GetVideoStats(context.Context, *VideoStatsRequest) (*VideoStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVideoStats not implemented")
}
func (UnimplementedReproduccionServiceServer) GetUserProgress(context.Context, *UserProgressRequest) (*UserProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProgress not implemented")
}
func (UnimplementedReproduccionServiceServer) mustEmbedUnimplementedReproduccionServiceServer() {}
func (UnimplementedReproduccionServiceServer) testEmbeddedByValue()                             {}

// UnsafeReproduccionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReproduccionServiceServer will
// result in compilation errors.
type UnsafeReproduccionServiceServer interface {
	mustEmbedUnimplementedReproduccionServiceServer()
}

func RegisterReproduccionServiceServer(s grpc.ServiceRegistrar, srv ReproduccionServiceServer) {
	// If the following call panics, it indicates UnimplementedReproduccionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReproduccionService_ServiceDesc, srv)
}

func _ReproduccionService_GetCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReproduccionServiceServer).GetCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReproduccionService_GetCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReproduccionServiceServer).GetCheckpoint(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReproduccionService_GetVideoStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReproduccionServiceServer).GetVideoStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReproduccionService_GetVideoStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReproduccionServiceServer).GetVideoStats(ctx, req.(*VideoStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReproduccionService_GetUserProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReproduccionServiceServer).GetUserProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReproduccionService_GetUserProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReproduccionServiceServer).GetUserProgress(ctx, req.(*UserProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReproduccionService_ServiceDesc is the grpc.ServiceDesc for ReproduccionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReproduccionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reproduccion.ReproduccionService",
	HandlerType: (*ReproduccionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCheckpoint",
			Handler:    _ReproduccionService_GetCheckpoint_Handler,
		},
		{
			MethodName: "GetVideoStats",
			Handler:    _ReproduccionService_GetVideoStats_Handler,
		},
		{
			MethodName: "GetUserProgress",
			Handler:    _ReproduccionService_GetUserProgress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "checkpoints.proto",
}
